"""
context_builder.py — Payload Assembler
Packages all scanner outputs into a clean, structured payload
ready to be sent to the NIM models.
"""

import json
from datetime import datetime, timezone


# ── Prompt Templates ──────────────────────────────────────────────────────────

CODER_SYSTEM_PROMPT = """You are ANAL (Autonomous aNALyst) — a ruthlessly rigorous Senior Software Architect and Code Auditor.

Your job is to analyze the project you are given and produce a deep, highly-detailed engineering analysis.

You will receive a structured context payload containing: the detected language, framework, hot source files, git history, logs, linter output, and config structure.

PRODUCE THE FOLLOWING SECTIONS EXACTLY ONCE:

## Project & Architecture Overview
What does this system do? What are its architectural strengths and concerns? Evaluate the tech stack.

## Critical Issues & Technical Debt
For EVERY major issue found (bugs, architecture, performance), provide:
- The exact File and Line Number(s).
- The Problem: What is wrong?
- Technical Analysis: Show the problematic code (use code blocks).
- Business Impact: Why does this matter?
- Recommended Solution: Show the fixed code or architectural pattern.
- Implementation Steps: A numbered list of exact steps to fix it.
- Effort Estimate & Risk Level.

## Security & Testing Posture
Are there exposed secrets, injection risks, or unsafe patterns? What is the current testing state, and what is the recommended testing strategy?

## Success Metrics
What are the current bottlenecks (memory, execution time, complexity)? What metrics will improve if the issues are fixed?

## END OF REPORT

RULES:
- Be exhaustively specific. Name exact files and line numbers.
- Provide actual code examples for your Technical Analysis and Recommended Solutions.
- Do NOT repeat yourself. Stop writing immediately after "## END OF REPORT".
- Keep your analysis factual, senior-level, and highly actionable."""


REPORTER_SYSTEM_PROMPT = """You are a Senior Engineering Analyst.
You receive raw, prioritized code analysis from an automated auditor. Your job is to format it into a comprehensive, professional Senior Engineering Analysis & Code Review.

Format your output EXACTLY matching the structure below. Do not skip sections.

```markdown
**Generated by:** Universal Project Improver (UPI)
**Reviewed by:** Senior Engineering Analyst
**Date:** [Current Date]
**Stack:** [Detected Language/Frameworks]
**Project:** [Project Name]
**Safety Validation:** ✅ PASSED
---

# Senior Engineering Analysis & Code Review

## Executive Summary
[1 paragraph summary of what the project does and its current state.]

**Overall Assessment:** [OPTIMAL / NEEDS ATTENTION / CRITICAL]  
**Codebase Maturity:** [Early / Mid / Enterprise]  
**Technical Debt Level:** [Low / Moderate / High]  
**Recommended Action:** [1 sentence recommendation]

---

## 1. Project Overview & Architecture Assessment
### What This System Does
[Explanation of project purpose]

### Current Architecture
[Strengths and weaknesses]

### Technology Stack Analysis
| Component | Technology | Assessment |
|-----------|------------|------------|
| Language | [Lang] | [Assessment] |

---

## 2. Critical Issues Requiring Immediate Attention
[For each critical issue found, use this exact format:]
### 🔴 CRITICAL #[N]: [Issue Title]
**File:** `[filename]`  
**The Problem:** [Description]
**Technical Analysis:**
```[language]
[Code showing the problem]
```
**Business Impact:** [Impact]
**Recommended Solution:**
```[language]
[Code showing the solution]
```
**Implementation Steps:**
1. [Step 1]
2. [Step 2]
**Effort Estimate:** [Time] | **Risk Level:** [Low/Med/High]
---

## 3. High-Priority Performance & Architecture Issues
[Same format as Critical Issues, using 🟠 HIGH]

## 4. Security & Safety Analysis
### 🟢 Security Posture: [GOOD / FAIR / POOR]
**Strengths:** [List]
**Recommendations:** [List]

## 5. Testing & Quality Assurance
**Current State:** [Assessment]
**Recommended Testing Strategy:** [Phases]

## 6. Prioritized Implementation Roadmap
### Sprint 1: Critical Stability
| Task | Priority | Effort | Impact |
|------|----------|--------|---------|
| [Task] | 🔴 | [Time] | [Impact] |

### Sprint 2: Architectural Cleanup
| Task | Priority | Effort | Impact |
|------|----------|--------|---------|
| [Task] | 🟠 | [Time] | [Impact] |

---

## 7. Success Metrics & KPIs
### Before Improvements
[List current bottlenecks/issues]
### After Improvements (Expected)
[List expected metrics]
### Business Impact
[List impact]

---

## 8. Conclusion & Recommendations
**Confidence Level:** High  
**Risk Assessment:** [Low/Medium/High]  
**Recommended Investment:** [Estimated total hours]

---
**Prepared by:** Senior Engineering Analyst  
**Review Type:** Comprehensive Architecture Assessment  
```

STOP HERE. Do not add any text after the document."""


def assemble(profile: dict, harvested: dict, lint_output: str) -> dict:
    """
    Build the final structured context payload.

    Returns:
        {
            "metadata": {...},
            "coder_system_prompt": str,
            "reporter_system_prompt": str,
            "user_payload": str,          # The full text sent to the Coder model
            "estimated_tokens": int,
        }
    """
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    # ── Format hot files ──────────────────────────────────────────────────────
    hot_files_text = ""
    for i, f in enumerate(harvested["hot_files"], 1):
        hot_files_text += f"\n--- FILE {i}: {f['path']} ---\n{f['content']}\n"

    # ── Format config structure ───────────────────────────────────────────────
    config_text = json.dumps(harvested["config_structure"], indent=2)

    # ── Assemble the user payload (Ingestion Template) ────────────────────────
    user_payload = f"""=== UNIVERSAL PROJECT IMPROVER — AUDIT CONTEXT ===
Timestamp : {timestamp}

PROJECT PROFILE
---------------
Language / Stack : {profile['language']} | Frameworks: {', '.join(profile['framework_hints']) or 'None detected'}
Description      : {profile['description']}
Git Enabled      : {profile['has_git']}
Target Path      : {profile['root_path']}

GIT HISTORY (Last {len(harvested['git_history'].splitlines())} Commits)
------------------------------
{harvested['git_history'] or 'No git history available.'}

HOT FILES — {len(harvested['hot_files'])} Most Recently Modified Source Files (The Active Zone)
-------------------------------------------------------------------------
{hot_files_text}

LOG FILE TAILS
--------------
{harvested['log_tail']}

CONFIG STRUCTURE (Keys Only for .env — No Secret Values)
---------------------------------------------------------
{config_text}

STATIC ANALYSIS (Linter Output)
---------------------------------
{lint_output}

=== END OF CONTEXT ===

INSTRUCTIONS:
Audit this project now. Find all critical bugs, architectural weaknesses, performance issues, and security risks.
Name exact file paths and line numbers wherever possible. Be ruthlessly specific — no generic advice.
"""

    estimated_tokens = len(user_payload) // 4
    
    # ── Token Limit Protection (Max ~60k tokens / 240k chars) ───────────────
    MAX_PAYLOAD_CHARS = 240_000
    if len(user_payload) > MAX_PAYLOAD_CHARS:
        print(f"  [Builder] ⚠️ Payload too large ({len(user_payload)} chars). Truncating to safe limits.")
        user_payload = user_payload[:MAX_PAYLOAD_CHARS] + "\n\n[... PAYLOAD TRUNCATED TO AVOID TOKEN OVERFLOW ...]\n"
        estimated_tokens = len(user_payload) // 4

    payload = {
        "metadata": {
            "timestamp":    timestamp,
            "project_name": _extract_project_name(profile["root_path"]),
            "language":     profile["language"],
            "frameworks":   profile["framework_hints"],
        },
        "coder_system_prompt":    CODER_SYSTEM_PROMPT,
        "reporter_system_prompt": REPORTER_SYSTEM_PROMPT,
        "user_payload":           user_payload,
        "estimated_tokens":       estimated_tokens,
    }

    print(f"  [Builder] Payload assembled. Estimated tokens: ~{estimated_tokens:,}")
    return payload


def _extract_project_name(root_path: str) -> str:
    """Extract a clean project name from the root directory path."""
    import os
    return os.path.basename(root_path.rstrip("/\\"))
