"""
reporter.py — Report Writer
Saves the final structured report to the target project directory.
"""

import os
from datetime import datetime, timezone


def save(report_text: str, project_path: str, metadata: dict, is_safe: bool, safety_note: str) -> str:
    """
    Write the final improvement report to the target project's root directory.

    Returns:
        str: The full path to the saved report file.
    """
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    filename = f"anal_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    output_path = os.path.join(project_path, filename)

    # ── Compose Header Block ─────────────────────────────────────────────────
    safety_badge = "✅ PASSED" if is_safe else "⚠️ FLAGGED"
    header = f"""---
**Generated by:** Universal Project Improver (UPI)
**Date:** {metadata.get('timestamp', today)}
**Language / Stack:** {metadata.get('language', 'Unknown')} | {', '.join(metadata.get('frameworks', [])) or 'No frameworks detected'}
**Target Project:** {metadata.get('project_name', 'Unknown')}
**Safety Validation:** {safety_badge} — {safety_note}
---

"""

    full_report = header + report_text

    # ── Write to File ────────────────────────────────────────────────────────
    try:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(full_report)
        print(f"\n  [Reporter] ✅ Report saved to: {output_path}")
    except PermissionError:
        # If the target project is write-protected, fall back to the working directory
        fallback_path = os.path.abspath(os.path.join(os.getcwd(), filename))
        with open(fallback_path, "w", encoding="utf-8") as f:
            f.write(full_report)
        print(f"\n  [Reporter] ⚠️  Could not write to target (permission denied).")
        print(f"  [Reporter]     Report saved to working directory instead: {fallback_path}")
        return fallback_path

    return output_path


def print_summary(report_text: str):
    """Print a short terminal summary (first 20 lines of the report)."""
    lines = report_text.splitlines()
    preview = "\n".join(lines[:25])
    print("\n" + "="*60)
    print("  REPORT PREVIEW (first 25 lines)")
    print("="*60)
    print(preview)
    if len(lines) > 25:
        print(f"\n  ... [{len(lines) - 25} more lines in saved file]")
    print("="*60 + "\n")
